### ISSUE TITLE
Combobulate

### ISSUE THREAD

**Issue by nils-schween** [ultronozm/tex-parens.el#1]
Hi, 

I tried various packages to move around in LaTeX buffers based on sexps, defuns etc. It its a rather difficult expierence.
Thanks for working into this direction.
I thought that you might be interested in learning about combobulate 
https://github.com/mickeynp/combobulate
It is based on tree-sitter and with a quick-search I also found a language grammar for LaTeX (there might be more then this one)
https://github.com/latex-lsp/tree-sitter-latex

You could integrate your efforts in combolutate, if you like. 
Thanks.

**Comment by ultronozm** [comment]
Hi Nils, thanks for the kind words and the suggestion.  I'd happily welcome further feedback on what you have in mind.  A couple quick thoughts:

1. tex-parens uses font-lock to detect math regions.  One of the main purported benefits of tree-sitter is to improve font-lock.  Incorporating tree-sitter into the tex modes would thus improve tex-parens without further invention.  This has not yet been done to my knowledge, but I'm not particularly motivated to do it, since the existing font-lock works reliably in my experience.

2. I took a quick look at the grammar that you linked to.  From what I can tell, it doesn't interact with, e.g., constructions like "\left\langle ... \right\rangle", which are important for me.

I'd be curious to hear if you see some specific upside to using tree-sitter and/or combobulate for tex (e.g., situations in which this package's behavior feels inaccurate or incomplete).

Thanks, best,

Paul

**Comment by nils-schween** [comment]
Actually I am quite impressed. Your package works very well. 

To one: As far as I understand tree-sitter creates a syntax tree and this tree can for example be used to do font-locking. But I think the idea is that you can use the syntax tree as a mean to understand the code (or markup language) in your buffer. This understanding can then be used to navigate, to fold etc. 
To two: It is likely that the Latex grammar is not complete. I guess that a lot of work goes into the creation of well working grammars. 

Well, my point is about unifying efforts. The idea of combobulate is to provide one package that gives us users a coherent experience in navigating sexps, defuns based a coherent approach, namely creating and interpreting syntax trees. 
Since I like the way your package works, I thought that you might be the right one to expand combobulate in the spirit of your package.

I would like to share the blog posts of the writer of combobulate with you
https://www.masteringemacs.org/

But never mind - I thought that you have missed combobulate and that if you had known it, it would have been your way to go. 
And thank you for your answer. You can close the issue if you like

**Comment by ultronozm** [comment]
Glad to hear, thanks!

Your point about unifying efforts is well-taken.  I'll keep an eye on combobulate.
